### PR TITLE
[#91] Fix: Move database migration right after the database initializing

### LINKED ISSUE #91: Fix: Move database migration right after the database initializing
## Issue

The current template runs the migration in [the Dockerfile](https://github.com/nimblehq/gin-templates/blob/develop/%7B%7Bcookiecutter.app_name%7D%7D/Dockerfile#L20) before the app is built. During development, if there's new code and the application is not deployed yet, running the migration there could produce unexpected errors.

## Expected

We should move the database migration right after the [database is initialized](https://github.com/nimblehq/gulf-approval-web/blob/develop/bootstrap/database.go#L17), just like we did in [Varun API project](https://github.com/nimblehq/varun-api/blob/develop/database/database.go#L33)

## Steps to reproduce

N/A

### PR DESCRIPTION
**Pull request by carryall**
Resolve https://github.com/nimblehq/gin-templates/issues/91

## What happened 👀

Move the database migration right after the [database is initialized](https://github.com/nimblehq/gulf-approval-web/blob/develop/bootstrap/database.go#L17), just like we did in [Varun API project](https://github.com/nimblehq/varun-api/blob/develop/database/database.go#L33)

## Insight 📝

N/A

## Proof Of Work 📹

All test passed

### CODE REVIEW

File: {{cookiecutter.app_name}}/database/database.go [hunk 1]
```diff
@@ -0,0 +1,68 @@
...
+	if gin.Mode() == gin.ReleaseMode {
+		return viper.GetString("DATABASE_URL")
+	}
+
+	return fmt.Sprintf("postgres://%s:%s@%s:%s/%s?sslmode=disable",
+		viper.GetString("db_username"),
+		viper.GetString("db_password"),
+		viper.GetString("db_host"),
+		helpers.GetStringConfig("db_port"),
+		helpers.GetStringConfig("db_name"),
```
Comment (hoangmirs) [inline {{cookiecutter.app_name}}/database/database.go:66]: Should we take this chance to drop the use of `config/app.toml` file? And change to use `.env` files instead.
With that file, we will get confused when adding new environment variables, as we don't know where we should put them

**Review by hoangmirs — APPROVED** [review]
LGTM with a small suggestion

**Review by Nihisil — APPROVED** [review]

**Review by sleepylee — APPROVED** [review]

File: {{cookiecutter.app_name}}/database/database.go (hunk 1 above)
Comment (carryall) [reply {{cookiecutter.app_name}}/database/database.go:66]: As this PR is opened for so long, let's do it in another PR. I've created [an issue](https://github.com/nimblehq/gin-templates/issues/97) to do it 🙇🏼
